/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Parrot.glb -o src/components/Parrot.jsx -r public -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/Parrot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.lambert2SG} />
      <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload('/models/Parrot.glb')
